version: 2

steps: &steps
  steps:
    - checkout
    - run: gem install bundler
    - run: bin/setup
    - run: bundle exec rake

jobs:

  ruby-2.6:
    docker:
      - image: circleci/ruby:2.6
    <<: *steps

  ruby-2.7:
    docker:
      - image: circleci/ruby:2.7
    <<: *steps

  ruby-head:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    <<: *steps

workflows:
  version: 2
  build:
    jobs:
      - ruby-2.6
      - ruby-2.7
      - ruby-head
